# Generated by Django 4.2 on 2023-05-06 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_siteuser_is_consultant_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileConsultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=200, verbose_name='Имя')),
                ('lastname', models.TextField(max_length=200, verbose_name='Фамилия')),
                ('surname', models.TextField(max_length=200, verbose_name='Отчество')),
                ('education', models.TextField(max_length=500, verbose_name='Образование')),
                ('experience', models.IntegerField(verbose_name='Опыт')),
                ('is_activate', models.BooleanField(verbose_name='Профиль активирован')),
                ('desription', models.TextField(max_length=500)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Изображение профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
