# Generated by Django 4.2 on 2023-05-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profileconsultant_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileconsultant',
            name='desription',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
    ]
