# Generated by Django 4.2 on 2023-05-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profileconsultant_desription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileconsultant',
            name='desription',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='profileconsultant',
            name='education',
            field=models.TextField(max_length=500, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='profileconsultant',
            name='experience',
            field=models.IntegerField(null=True, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='profileconsultant',
            name='firstname',
            field=models.TextField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profileconsultant',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics', verbose_name='Изображение профиля'),
        ),
        migrations.AlterField(
            model_name='profileconsultant',
            name='is_activate',
            field=models.BooleanField(null=True, verbose_name='Профиль активирован'),
        ),
        migrations.AlterField(
            model_name='profileconsultant',
            name='lastname',
            field=models.TextField(max_length=200, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profileconsultant',
            name='surname',
            field=models.TextField(max_length=200, null=True, verbose_name='Отчество'),
        ),
    ]
