# Generated by Django 4.2 on 2023-05-08 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profileconsultant_desription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileconsultant',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Изображение профиля'),
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=200, null=True, verbose_name='Имя')),
                ('lastname', models.TextField(max_length=200, null=True, verbose_name='Фамилия')),
                ('surname', models.TextField(max_length=200, null=True, verbose_name='Отчество')),
                ('bday', models.DateField(default='01.01.1990', verbose_name='Дата рождения')),
                ('height', models.IntegerField(default=0, verbose_name='Рост (см)')),
                ('weight', models.FloatField(default=0, verbose_name='Вес (кг)')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Изображение профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
