# Generated by Django 4.2 on 2023-05-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profileuser_sex_alter_profileuser_bday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='sex',
            field=models.TextField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True, verbose_name='Пол'),
        ),
    ]
